# Generated by Django 5.0.10 on 2025-02-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(default='Unknown', max_length=100)),
                ('item_name', models.CharField(default='Unknown', max_length=255)),
                ('unit', models.CharField(default='Unit', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('phonepe_upi', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('card_pmt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('zomato', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('swiggy', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bms', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('expenditure', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_sale', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item_type', models.CharField(default='Unknown', max_length=255)),
                ('item_name', models.CharField(default='Unknown', max_length=255)),
                ('unit', models.CharField(default='Unit', max_length=100)),
                ('closing', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('required', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delivered', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
