# Generated by Django 5.0.10 on 2025-03-09 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypurchase',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 3, 9, 12, 56, 59, 940772)),
        ),
        migrations.AlterField(
            model_name='dailypurchase',
            name='item_name',
            field=models.CharField(default='Unknown Item', max_length=255),
        ),
        migrations.AlterField(
            model_name='dailypurchase',
            name='item_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dailypurchase',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailypurchase',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailypurchase',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailypurchase',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailypurchase',
            name='unit',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='salesentry',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salesentry',
            name='total_sale',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockrequisition',
            name='closing',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockrequisition',
            name='delivered',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockrequisition',
            name='item_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stockrequisition',
            name='item_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stockrequisition',
            name='required',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockrequisition',
            name='unit',
            field=models.CharField(max_length=100),
        ),
    ]
